services:
  beets:
    image: lscr.io/linuxserver/beets:latest
    container_name: beets
    environment:
      # Update as needed
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./config:/config
      - ./plugins:/plugins
      - ./scripts:/config/custom-cont-init.d
      - /Users/edward/Downloads/FakeLib:/audiobooks
      # - /Volumes/audiobooks/edward:/audiobooks
      - /Users/edward/Downloads/___untagged:/untagged
    restart: unless-stopped
